import { ContactBand, Eyebrow, PageHero } from '../components/Shared'
import { Reveal } from '../components/Motion'
import { images } from '../data/site'

const articles = [
  ['World Water Summit — Madrid, Spain', '2ML Consulting participated in the Global Water Summit in Madrid, Spain, joining water sector leaders, utilities, development partners and policymakers from around the world to discuss emerging trends, innovative solutions and the future of sustainable water management. The summit provided a valuable platform to exchange experiences on utility transformation, institutional strengthening and climate resilience.'],
  ['Uganda Water and Environment Week (UWEWK)', 'As part of the Uganda Water and Environment Week, 2ML Consulting hosted a successful side event at the Ministry of Water and Environment Headquarters. The session brought together government representatives, development partners, utilities and sector professionals to discuss “Harnessing Science, Technology, Innovation and Capacity Development to Transform Water Management.” The event highlighted practical lessons from the Bor Water Supply System in South Sudan and reinforced the importance of innovation and institutional capacity in delivering sustainable water services.'],
  ['Victoria Basin International Conference and Exhibition (Upcoming)', '2ML Consulting plans to participate in the upcoming Victoria Basin International Conference and Exhibition (VBICE) in Kisumu, Kenya. The conference will provide another opportunity to engage with regional stakeholders, showcase our expertise in institutional transformation and WASH sector development, strengthen partnerships and contribute to discussions on sustainable water resources management and regional development.'],
]

export function InsightsPage() { return <><PageHero kicker="News & insights" title={<>Connecting, learning<br /><em className="font-serif font-medium text-[#8C1E2D]">and shaping the future.</em></>} description="At 2ML Consulting Limited, we actively participate in leading regional and international conferences, forums and knowledge-sharing platforms that advance innovation, strengthen partnerships and shape the future of the water, sanitation and hygiene sector." picture={images.community} /><section className="mx-auto max-w-[1440px] px-5 py-20 sm:px-8 lg:px-12 lg:py-32"><Reveal><Eyebrow>Latest from 2ML</Eyebrow></Reveal><div className="mt-12 grid gap-8 md:grid-cols-3">{articles.map(([title, copy], index) => <Reveal key={title} delay={index * 100} className="border-t-2 border-[#8C1E2D] pt-7"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#8C1E2D]">Sector dialogue</p><h2 className="mt-5 text-3xl font-semibold leading-[1] tracking-[-.05em]">{title}</h2><p className="mt-5 leading-7 text-black/65">{copy}</p></Reveal>)}</div></section><section className="bg-[#111111] text-white"><div className="mx-auto max-w-[1440px] px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><Reveal><p className="text-xs font-bold uppercase tracking-[.18em] text-[#F5953B]">Stay connected</p><h2 className="mt-6 max-w-4xl text-4xl font-semibold leading-[.98] tracking-[-.065em] sm:text-6xl">Follow our latest news, project milestones, conference participation and thought leadership as we continue partnering with governments, utilities and development partners to transform institutions and improve water and sanitation services across Africa and beyond.</h2></Reveal></div></section><ContactBand /></> }
